<template>
  <Layout>
    <!-- Replace everything inside this Layout with your own content -->
    <!-- The main container CSS classes are in `src/layouts/Default.vue` -->

    <div class="mt-8 items-center">
      <h1 class="font-maintitle text-5xl sm:text-7xl block text-center sm:pr-8 text-gray-700">
        {{ $static.metadata.siteName }}
      </h1>
    </div>

    <h2>About the project</h2>
    <p>
        This website is a school project in 12th grade English Advanced Class (LK) at the Pelizaeus Gymnasium in Paderborn.
        <br />Sonnets were generated by the <a href="https://openai.com/">GTP-3 AI by OpenAI</a>. This website stands in no affiliation with OpenAI in any way.
    </p>
    <h2>The Website</h2>
    <p>
        The website for this project was build and expanded upon the awesome <a href="https://github.com/Uninen/gridsome-starter-tulip">starter</a> of <a href="https://twitter.com/uninen">Ville Säävuori</a>.
        It is completely open-source and available on <a href="https://github.com/lukaslangrock/nigeria-history">GitHub</a>. Hosted on <a href="https://vercel.com/">Vercel</a>.
    </p>

    <h3>I hope that you enjoy this creation! ❤</h3>

    <BackToHome />
  </Layout>
</template>

<static-query>
query {
  metadata {
    siteName
  }
}
</static-query>

<script>
import BackToHome from "@/components/BackToHome";

export default {
  metaInfo: {
    title: "About the project"
  },
  components: {
    BackToHome
  }
};
</script>
